ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_cpf TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS zip_code TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_number TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_complement TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_neighborhood TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_city TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_state TEXT;
